// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyfhfptoiipqmuwtobgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZmhmcHRvaWlwcW11d3RvYmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTQ1OTYsImV4cCI6MjA2NTYzMDU5Nn0.DVlTNKrYSksAQyLknuG9NOGvyADBtJIxRyLPZF7rBRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);